name: Codecov

inputs:
    CODECOV_TOKEN:
        required: false
        description: "Provides CodeCov token"

runs:
    using: "composite"
    steps:
      - name: Upload coverage reports to Codecov
        if: ${{ inputs.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v5
        with:
            token: ${{ inputs.CODECOV_TOKEN }}
